### ISSUE TITLE
Github is blocking

### ISSUE THREAD

**Issue by gregsdennis** [tugberkugurlu/bitbucket-issues-to-github#1]
So it seems that Github has instituted a policy that now blocks the rapid updates created by this app.  Not really a problem with the app (which works fine), but thought it warranted some mention.

**Comment by tugberkugurlu** [comment]
> the rapid updates created by this app

Oh, interesting 😄 was that specific to this project or a generic policy of the API?

**Comment by gregsdennis** [comment]
I think it was a generic policy.  I used this once for a few of my projects.  Thanks for your work.

**Comment by tugberkugurlu** [comment]
Great 👍, I think the `Thread.Sleep` which is put on #4 solved this too.
